dependencies:
- name: elasticsearch
  version: ^1.32.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
- name: kibana
  version: ^3.2.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kibana.enabled