# Default values for complex-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

worker:
  enabled: true
  image: aleksaspielikis/multi-worker

client:
  enabled: true
  replicas: 3
  image: aleksaspielikis/multi-client

server:
  enabled: true
  replicas: 3
  image: aleksaspielikis/multi-server

redis:
  enabled: true
  clusterPort: 6379

metricbeat:
  enabled: true

kibana:
  enabled: true
  env:
    ELASTICSEARCH_HOSTS: http://{{ .Release.Name }}-elasticsearch-client:9200

elasticsearch:
  enabled: true
  antiAffinity: "soft"
  esJavaOpts: -Xmx256m -Xms256m
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

  # Request smaller persistent volumes.
  persistence:
    size: 100M

postgres:
  enabled: true
  clusterPort: 5432
  storage: 2Gi
  secretKeyRef:
    name: pgpassword
    key: PGPASSWORD

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  expose:
    client:
      path: /?(.*)
      clusterPort: 3000
    server:
      path: /api/?(.*)
      clusterPort: 5000
